all:
	cc -o ret0 ret0.c
	cc -o ret1 ret1.c
	cc -o exit0 exit0.c
	cc -o exit1 exit1.c
	cc -o crash crash.c
	cc -o alarm alarm.c
	cc -o wait wait.c

clean:
	rm -f ret0 ret1 exit0 exit1 crash alarm wait
