#ifndef _UTITLS_CONFIG_H
#define _UTITLS_CONFIG_H

#define CONFIG_HELLO_REAL 0
#define CONFIG_HELLO_PMODE 0
#define CONFIG_HELLO_LINK 0
#define CONFIG_HELLO_PAGING0 0
#define CONFIG_HELLO_PAGING1 0
#define CONFIG_HELLO_VGA 0
#define CONFIG_HELLO_PRINTF 0

#define CONFIG_HW_IDT 0
#define CONFIG_HW_KBD 0
#define CONFIG_HW_CLOCK 0
#define CONFIG_HW_HD0 0
#define CONFIG_HW_HD1 0

#define CONFIG_AB_NICE 0
#define CONFIG_AB_COND 0
#define CONFIG_AB_PREMPT 0

#define CONFIG_UTILS_LIST 0
#define CONFIG_UTILS_CACHE 0
#define CONFIG_UTILS_FIFO 0
#define CONFIG_UTILS_BITMAP 0
#define CONFIG_UTILS_STRTOK 0

#define CONFIG_MM_ALLOC_PAGE 0
#define CONFIG_MM_ALLOC_MEMORY 0
#define CONFIG_MM_PGTBL 0

#define CONFIG_FS_BUFFER 0
#define CONFIG_FS_INODE 0
#define CONFIG_FS_FS 0
#define CONFIG_FS_FORK 0

#define CONFIG_TASK_NICE 0
#define CONFIG_TASK_COND 0
#define CONFIG_TASK_FORK 0
#define CONFIG_TASK_EXEC 0
#define CONFIG_TASK_WAIT 0
#define CONFIG_TASK_EXIT 0
#define CONFIG_TASK_PREMPT 0
#define CONFIG_TASK_IDLE 0

#define CONFIG_OS_SHELL 0
#define CONFIG_OS_ARGV 0
#define CONFIG_OS_DIR 0

#define CONFIG_OS_LAMBDA 0
#define CONFIG_OS_PIPE 0
#define CONFIG_OS_MEMORY_DEVCIE 0
#define CONFIG_OS_TTY 0

#define CONFIG_OS_PART 0
#define CONFIG_OS_MOUNT 0
#define CONFIG_OS_RAM_DISK 0

#define CONFIG_OS_DEMAND 0
#define CONFIG_OS_COW 0
#define CONFIG_OS_SWAP 0

#define CONFIG_OS_UID 0
#define CONFIG_OS_EUID 0
#define CONFIG_OS_LOGIN 0

#define CONFIG_NET_SOCKET 1
#define CONFIG_NET_UNIX_DGRAM 0
#define CONFIG_NET_UNIX_STREAM 0
#define CONFIG_NET_LOOP 0
#define CONFIG_NET_NIC 0
#define CONFIG_NET_ARP 0
#define CONFIG_NET_IP 0
#define CONFIG_NET_UDP 0
#define CONFIG_NET_TCP 0

#endif
